"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LMS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const [DropDown,setDropDown]=useState(false)


  return (
    <html lang="en">
      <body className={inter.className}>
       
<nav className="bg-white border-gray-200  absolute w-[100%] z-10">
  <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <Link href="/" className="flex items-center">

        <span className="self-center text-2xl font-[Oswald] font-semibold whitespace-nowrap dark:text-black">LMS</span>
    </Link>
    <button data-collapse-toggle="navbar-default" type="button" 
    className="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false"
    onClick={()=>setDropDown(!DropDown)}
    // onTouchStart={()=>setDropDown(!DropDown)}
    >
        <span className="sr-only">Open main menu</span>
        <svg className="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div className={`${DropDown ? 'block' : 'hidden'} w-full md:block md:w-auto `} id="navbar-default">
      <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:border-gray-700">
        <li>
          <Link href="/" className="block py-2 pl-3 pr-4 font-bold text-white bg-[#0ABEA9] rounded md:bg-transparent md:text-[#0ABEA9] md:p-0 dark:text-white md:dark:text-[#0ABEA9]" aria-current="page">Home</Link>
        </li>
        <li>
          <Link href="/aboutus" className="block py-2 pl-3 pr-4 font-bold text-black   rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-[#0ABEA9] md:p-0 dark:text-black md:dark:hover:text-[#0ABEA9] dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</Link>
        </li>
        <li>
          <Link href="#" className="block py-2 pl-3 pr-4 font-bold text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-[#0ABEA9] md:p-0 dark:text-black md:dark:hover:text-[#0ABEA9] dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</Link>
        </li>
        <li>
          <Link href="/signup" className="block py-2 pl-3 pr-4 font-bold text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-[#0ABEA9] md:p-0 dark:text-black md:dark:hover:text-[#0ABEA9] dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Register</Link>
        </li>
        <li>
          <Link href="/login" className="block py-2 pl-3 pr-4 font-bold text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-[#0ABEA9] md:p-0 dark:text-black md:dark:hover:text-[#0ABEA9] dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Login</Link>
        </li>
      </ul>
    </div>
  </div>
</nav>

        {children}</body>
    </html>
  )
}
